/**
 * StudentOS Junova AI — Domain Types
 *
 * Core types for the Junova AI feature: AI Teachers, Teacher DNA,
 * Conversations, and Messages.
 *
 * @see docs/DATABASE.md for the Firestore schema reference.
 */

// ---------------------------------------------------------------------------
// Teacher DNA (Sprint 4.2)
// ---------------------------------------------------------------------------

/**
 * Teacher DNA — 11 personality traits that modulate AI responses.
 * Each trait is a number 0–100 (0 = low, 100 = high).
 */
export interface TeacherDNA {
  /** How warm and approachable the teacher is. */
  friendliness: number;
  /** How demanding the teacher is about correctness and rigor. */
  strictness: number;
  /** How often the teacher uses humor to lighten the mood. */
  humor: number;
  /** How detailed explanations are (brief vs thorough). */
  explanationDepth: number;
  /** How patient the teacher is with repeated questions. */
  patience: number;
  /** How much the teacher encourages and motivates the student. */
  motivation: number;
  /** How often the teacher uses emojis in responses. */
  emojiUsage: number;
  /** How often the teacher uses stories / analogies. */
  storytelling: number;
  /** How often the teacher connects concepts to real-life examples. */
  realLifeExamples: number;
  /** When true, the teacher prioritizes exam-style questions and marks. */
  examFocused: boolean;
  /** Difficulty level the teacher targets. */
  difficulty: 'beginner' | 'intermediate' | 'advanced';
}

/** Default DNA for a new teacher. */
export const DEFAULT_DNA: TeacherDNA = {
  friendliness: 70,
  strictness: 50,
  humor: 40,
  explanationDepth: 60,
  patience: 80,
  motivation: 70,
  emojiUsage: 20,
  storytelling: 50,
  realLifeExamples: 60,
  examFocused: false,
  difficulty: 'intermediate',
};

// ---------------------------------------------------------------------------
// AI Teacher (Sprint 4.1)
// ---------------------------------------------------------------------------

/** Personality preset — a starting DNA template. */
export type PersonalityPreset =
  | 'friendly-mentor'
  | 'strict-professor'
  | 'study-buddy'
  | 'exam-coach'
  | 'creative-guide'
  | 'custom';

/** Teaching style — modulates how the teacher delivers content. */
export type TeachingStyle = 'socratic' | 'lecture' | 'hands-on' | 'visual' | 'story-based';

/**
 * AI Teacher — a configurable AI persona that students chat with.
 * Stored in Firestore under `junova_teachers/{teacherId}`.
 */
export interface AITeacher {
  id: string;
  /** Owner UID (Firebase Auth). */
  uid: string;
  name: string;
  /** Avatar image URL (Firebase Storage path or null for initials). */
  avatarURL: string | null;
  /** Subject this teacher specializes in. */
  subject: string;
  /** Personality preset used to initialize DNA. */
  preset: PersonalityPreset;
  /** How this teacher delivers content. */
  teachingStyle: TeachingStyle;
  /** Short biography / description. */
  bio: string;
  /** Theme color — hex string used for UI accents. */
  themeColor: string;
  /** The personality configuration. */
  dna: TeacherDNA;
  createdAt: number;
  updatedAt: number;
}

// ---------------------------------------------------------------------------
// Conversations & Messages (Sprint 4.3)
// ---------------------------------------------------------------------------

/** A chat conversation between a student and an AI teacher. */
export interface Conversation {
  id: string;
  uid: string;
  /** The AI teacher this conversation is with. */
  teacherId: string;
  title: string;
  /** Preview text for the sidebar (last message snippet). */
  lastMessagePreview: string;
  messageCount: number;
  /** Pinned conversations appear at the top of the sidebar. */
  pinned: boolean;
  createdAt: number;
  updatedAt: number;
}

/** Role of a message sender. */
export type MessageRole = 'user' | 'assistant';

/** A single message in a conversation. */
export interface Message {
  id: string;
  conversationId: string;
  role: MessageRole;
  content: string;
  /** File attachments (images, PDFs) — Firebase Storage URLs. */
  attachments?: MessageAttachment[];
  /** When true, the message is being streamed (not yet complete). */
  isStreaming?: boolean;
  /** When true, the response can be regenerated. */
  canRegenerate?: boolean;
  /** Suggested follow-up questions (assistant messages only). */
  suggestions?: string[];
  /** Review engine metadata (assistant messages only — set after review). */
  review?: ChatStreamChunk['review'];
  createdAt: number;
}

/** File attachment on a message. */
export interface MessageAttachment {
  type: 'image' | 'pdf';
  url: string;
  filename: string;
  /** For images: a text description generated by VLM (future). */
  description?: string;
}

// ---------------------------------------------------------------------------
// Chat request / response (API layer)
// ---------------------------------------------------------------------------

/** Request body for the streaming chat API. */
export interface ChatRequest {
  conversationId: string;
  teacherId: string;
  /** Full teacher config (sent from client since it was already fetched). */
  teacher: AITeacher;
  message: string;
  /** Previous messages for context (last N messages). */
  history: { role: MessageRole; content: string }[];
  /** File attachments to include in the message. */
  attachments?: MessageAttachment[];
  /** Student memory for personalization (Phase 2). */
  memory?: StudentMemory | null;
}

/** A chunk in the streaming response. */
export interface ChatStreamChunk {
  type:
    | 'delta'
    | 'done'
    | 'error'
    | 'suggestions'
    | 'review-correction'
    | 'review-enhanced'
    | 'review-meta';
  content?: string;
  suggestions?: string[];
  error?: string;
  /** Review engine metadata (present when type starts with 'review-'). */
  review?: {
    verdict: 'approved' | 'approved-with-enhancements' | 'rewritten' | 'rejected';
    scores: {
      overallQuality: number;
      accuracy: number;
      safety: number;
      childFriendly: number;
      boardExam: number;
      confidence: number;
    };
    wasRewritten?: boolean;
    issues?: Array<{
      agent: string;
      severity: 'info' | 'warning' | 'error' | 'critical';
      description: string;
      suggestedFix?: string;
    }>;
  };
}

// ---------------------------------------------------------------------------
// Long-Term Memory (Sprint 4.4 — Phase 2)
// ---------------------------------------------------------------------------

/**
 * Student's long-term memory — a single document per user at
 * `junova_memory/{uid}`. The AI reads this before responding to provide
 * personalized, context-aware answers.
 */
export interface StudentMemory {
  /** Document ID = user UID. */
  uid: string;

  // --- Identity & profile ---
  /** Student's display name (mirrored from user profile for AI context). */
  displayName: string | null;
  /** Student's grade or year level. */
  grade: string | null;

  // --- Learning preferences ---
  /** How the student learns best (visual, auditory, reading/writing, kinesthetic). */
  learningStyle: string | null;
  /** Preferred language for explanations (ISO code, e.g. "en", "es", "fr"). */
  preferredLanguage: string;
  /** Study preferences — time of day, session length, breaks, etc. */
  studyPreferences: {
    preferredStudyTime: 'morning' | 'afternoon' | 'evening' | 'night' | null;
    sessionLengthMinutes: number;
    breakFrequencyMinutes: number;
    prefersDetailedExplanations: boolean;
    prefersExamplesFirst: boolean;
  };

  // --- Academic state ---
  /** Subjects the student is studying. */
  subjects: string[];
  /** Topics the student struggles with (auto-detected + manual). */
  weakTopics: string[];
  /** Topics the student has mastered. */
  strongTopics: string[];
  /** Exam goals — e.g. "Score 90% on AP Calculus". */
  examGoals: string[];
  /** Daily study routine description. */
  dailyRoutine: string | null;

  // --- Conversation intelligence ---
  /** Summary of recent conversations (auto-generated, rolling). */
  conversationSummary: string | null;
  /** Last N topics discussed (for context continuity). */
  recentTopics: string[];
  /** Revision history — topics + dates for spaced repetition. */
  revisionHistory: RevisionEntry[];

  // --- Preferences ---
  /** Favorite AI Teacher ID. */
  favoriteTeacherId: string | null;

  // --- Timestamps ---
  createdAt: number;
  updatedAt: number;
  /** When the conversation summary was last regenerated. */
  lastSummaryUpdate: number | null;
}

/** A single revision entry — tracks when a topic was last reviewed. */
export interface RevisionEntry {
  topic: string;
  subject: string;
  lastReviewed: number;
  /** 0–100 confidence level. */
  confidence: number;
}

/** Default memory for a new user. */
export const DEFAULT_MEMORY: Omit<StudentMemory, 'uid'> = {
  displayName: null,
  grade: null,
  learningStyle: null,
  preferredLanguage: 'en',
  studyPreferences: {
    preferredStudyTime: null,
    sessionLengthMinutes: 25,
    breakFrequencyMinutes: 5,
    prefersDetailedExplanations: true,
    prefersExamplesFirst: false,
  },
  subjects: [],
  weakTopics: [],
  strongTopics: [],
  examGoals: [],
  dailyRoutine: null,
  conversationSummary: null,
  recentTopics: [],
  revisionHistory: [],
  favoriteTeacherId: null,
  createdAt: 0,
  updatedAt: 0,
  lastSummaryUpdate: null,
};

// ---------------------------------------------------------------------------
// AI Recommendations (Sprint 4.4 — Phase 2)
// ---------------------------------------------------------------------------

/**
 * Personalized recommendations generated by Junova AI based on the student's
 * memory. Single document per user at `junova_recommendations/{uid}`.
 */
export interface AIRecommendations {
  /** Document ID = user UID. */
  uid: string;

  // --- Study recommendations ---
  /** Next chapter/topic the student should study. */
  nextChapter: string | null;
  /** Topics that need revision (spaced repetition). */
  revisionTopics: string[];
  /** Practice recommendations (exercises, quizzes, past papers). */
  practiceRecommendations: string[];
  /** Daily learning goals (2–5 actionable items). */
  dailyGoals: string[];
  /** Personalized study path — ordered list of topics. */
  studyPath: string[];

  // --- Analytics ---
  /** 0–100 exam readiness score. */
  examReadinessScore: number;
  /** Human-readable explanation of the readiness score. */
  examReadinessExplanation: string | null;

  // --- Personalization ---
  /** Recommended AI Teacher ID based on learning style + subjects. */
  recommendedTeacherId: string | null;
  /** Why this teacher is recommended. */
  recommendedTeacherReason: string | null;
  /** Daily motivational insight (1–2 sentences). */
  motivationalInsight: string | null;

  // --- Timestamps ---
  createdAt: number;
  updatedAt: number;
  /** When recommendations were last regenerated. */
  generatedAt: number;
}

/** Default recommendations for a new user. */
export const DEFAULT_RECOMMENDATIONS: Omit<AIRecommendations, 'uid'> = {
  nextChapter: null,
  revisionTopics: [],
  practiceRecommendations: [],
  dailyGoals: [],
  studyPath: [],
  examReadinessScore: 0,
  examReadinessExplanation: null,
  recommendedTeacherId: null,
  recommendedTeacherReason: null,
  motivationalInsight: null,
  createdAt: 0,
  updatedAt: 0,
  generatedAt: 0,
};

/** Result of a recommendation generation operation. */
export interface RecommendationResult {
  success: boolean;
  data?: AIRecommendations;
  error?: { code: string; message: string };
}

// ---------------------------------------------------------------------------
// Voice Preferences (Sprint 4.5 — Phase 3)
// ---------------------------------------------------------------------------

/**
 * User's voice preferences — single document per user at
 * `junova_voice_preferences/{uid}`. Controls TTS voice, rate, pitch, etc.
 */
export interface VoicePreferences {
  uid: string;
  /** Whether voice conversations are enabled. */
  enabled: boolean;
  /** Selected voice URI (from SpeechSynthesis.getVoices()). */
  voiceURI: string | null;
  /** Speech rate (0.5–2.0, default 1.0). */
  rate: number;
  /** Speech pitch (0–2.0, default 1.0). */
  pitch: number;
  /** Speech volume (0–1.0, default 1.0). */
  volume: number;
  /** Language code for STT + TTS (e.g. "en-US", "es-ES"). */
  language: string;
  /** Automatically speak AI responses. */
  autoSpeak: boolean;
  createdAt: number;
  updatedAt: number;
}

export const DEFAULT_VOICE_PREFERENCES: Omit<VoicePreferences, 'uid'> = {
  enabled: false,
  voiceURI: null,
  rate: 1.0,
  pitch: 1.0,
  volume: 1.0,
  language: 'en-US',
  autoSpeak: true,
  createdAt: 0,
  updatedAt: 0,
};

// ---------------------------------------------------------------------------
// Live Session Settings (Sprint 4.5 — Phase 3)
// ---------------------------------------------------------------------------

/** Avatar visual style. */
export type AvatarStyle = 'minimal' | 'geometric' | 'friendly';

/** Avatar facial expression — drives the expression animation. */
export type AvatarExpression =
  'neutral' | 'happy' | 'focused' | 'thinking' | 'encouraging' | 'surprised' | 'speaking';

/**
 * Live session settings — single document per user at
 * `junova_live_sessions/{uid}`. Controls avatar appearance + behavior.
 */
export interface LiveSessionSettings {
  uid: string;
  /** Avatar visual style. */
  avatarStyle: AvatarStyle;
  /** How expressive the avatar is (0–100). */
  expressionIntensity: number;
  /** Animation speed multiplier (0.5–2.0, default 1.0). */
  animationSpeed: number;
  /** Whether the live teacher is in fullscreen mode. */
  fullscreenMode: boolean;
  /** Whether the whiteboard is visible. */
  whiteboardEnabled: boolean;
  /** Whether eye-contact tracking is enabled. */
  eyeContactEnabled: boolean;
  /** Whether hand gestures are enabled. */
  gesturesEnabled: boolean;
  createdAt: number;
  updatedAt: number;
}

export const DEFAULT_LIVE_SESSION_SETTINGS: Omit<LiveSessionSettings, 'uid'> = {
  avatarStyle: 'friendly',
  expressionIntensity: 70,
  animationSpeed: 1.0,
  fullscreenMode: false,
  whiteboardEnabled: false,
  eyeContactEnabled: true,
  gesturesEnabled: true,
  createdAt: 0,
  updatedAt: 0,
};

// ---------------------------------------------------------------------------
// Voice Conversation State (Sprint 4.5 — Phase 3)
// ---------------------------------------------------------------------------

/** State machine for a voice conversation. */
export type VoiceConversationState =
  'idle' | 'listening' | 'processing' | 'speaking' | 'paused' | 'error';

/** A message in a voice conversation (transcript). */
export interface VoiceMessage {
  role: 'user' | 'assistant';
  content: string;
  timestamp: number;
}
