/**
 * StudentOS Junova AI — Teacher Service
 *
 * CRUD operations for AI Teacher profiles. Uses the centralized Firestore
 * helpers from Sprint 1.2. All operations are scoped to the authenticated
 * user's UID.
 *
 * @see src/firebase/firestore-helpers.ts
 * @see src/firebase/constants.ts — COLLECTIONS.JUNOVA_TEACHERS
 */

import { COLLECTIONS, firestoreHelpers, type StudentOSFirebaseError } from '@/firebase';
import { where, orderBy, type Unsubscribe } from 'firebase/firestore';
import { normalizeFirebaseError } from '@/firebase/error-handler';
import type { AITeacher, TeacherDNA } from '../types';
import { DEFAULT_DNA } from '../types';
import { PERSONALITY_PRESETS } from '../constants';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

export interface TeacherServiceResult<T> {
  success: boolean;
  data?: T;
  error?: StudentOSFirebaseError;
}

export interface CreateTeacherInput {
  name: string;
  avatarURL?: string | null;
  subject: string;
  preset: AITeacher['preset'];
  teachingStyle: AITeacher['teachingStyle'];
  bio: string;
  themeColor: string;
  dna?: TeacherDNA;
}

export interface UpdateTeacherInput extends Partial<CreateTeacherInput> {
  avatarURL?: string | null;
}

// ---------------------------------------------------------------------------
// Create
// ---------------------------------------------------------------------------

/**
 * Create a new AI Teacher profile in Firestore.
 * The document ID is auto-generated by Firestore.
 */
export async function createTeacher(
  uid: string,
  input: CreateTeacherInput,
): Promise<TeacherServiceResult<AITeacher>> {
  try {
    const dna =
      input.dna ??
      (input.preset !== 'custom' ? PERSONALITY_PRESETS[input.preset].dna : DEFAULT_DNA);

    const now = Date.now();
    const teacherData = {
      uid,
      name: input.name,
      avatarURL: input.avatarURL ?? null,
      subject: input.subject,
      preset: input.preset,
      teachingStyle: input.teachingStyle,
      bio: input.bio,
      themeColor: input.themeColor,
      dna,
      createdAt: now,
      updatedAt: now,
    };

    const result = await firestoreHelpers.createDocument(COLLECTIONS.JUNOVA_TEACHERS, teacherData);
    if (!result.success || !result.data) {
      return { success: false, error: result.error };
    }

    return {
      success: true,
      data: { id: result.data, ...teacherData } as AITeacher,
    };
  } catch (err) {
    return { success: false, error: normalizeFirebaseError(err) };
  }
}

// ---------------------------------------------------------------------------
// Read
// ---------------------------------------------------------------------------

/** Get a single teacher by ID. */
export async function getTeacher(
  teacherId: string,
): Promise<TeacherServiceResult<AITeacher | null>> {
  try {
    const result = await firestoreHelpers.getDocument<AITeacher>(
      COLLECTIONS.JUNOVA_TEACHERS,
      teacherId,
    );
    if (!result.success) return { success: false, error: result.error };
    return { success: true, data: result.data };
  } catch (err) {
    return { success: false, error: normalizeFirebaseError(err) };
  }
}

/** Get all teachers owned by a user. */
export async function getTeachers(uid: string): Promise<TeacherServiceResult<AITeacher[]>> {
  return firestoreHelpers.queryCollection<AITeacher>(
    COLLECTIONS.JUNOVA_TEACHERS,
    where('uid', '==', uid),
    orderBy('createdAt', 'desc'),
  );
}

/**
 * Subscribe to a user's teachers in real-time.
 * @returns unsubscribe function
 */
export function subscribeToTeachers(
  uid: string,
  onNext: (teachers: AITeacher[]) => void,
  onError?: (error: StudentOSFirebaseError) => void,
): Unsubscribe {
  return firestoreHelpers.subscribeToQuery<AITeacher>(
    COLLECTIONS.JUNOVA_TEACHERS,
    onNext,
    onError,
    where('uid', '==', uid),
    orderBy('createdAt', 'desc'),
  );
}

// ---------------------------------------------------------------------------
// Update
// ---------------------------------------------------------------------------

/** Update a teacher's fields. */
export async function updateTeacher(
  teacherId: string,
  updates: UpdateTeacherInput,
): Promise<TeacherServiceResult<void>> {
  try {
    const payload = { ...updates, updatedAt: Date.now() };
    return firestoreHelpers.updateDocument(COLLECTIONS.JUNOVA_TEACHERS, teacherId, payload);
  } catch (err) {
    return { success: false, error: normalizeFirebaseError(err) };
  }
}

// ---------------------------------------------------------------------------
// Delete
// ---------------------------------------------------------------------------

/** Delete a teacher by ID. */
export async function deleteTeacher(teacherId: string): Promise<TeacherServiceResult<void>> {
  try {
    return firestoreHelpers.deleteDocument(COLLECTIONS.JUNOVA_TEACHERS, teacherId);
  } catch (err) {
    return { success: false, error: normalizeFirebaseError(err) };
  }
}

// ---------------------------------------------------------------------------
// Barrel
// ---------------------------------------------------------------------------

export const teacherService = {
  createTeacher,
  getTeacher,
  getTeachers,
  subscribeToTeachers,
  updateTeacher,
  deleteTeacher,
} as const;
